language: node_js
node_js:
  - '6'
before_install:
  - export TZ='Asia/Shanghai'
  - cp themes/_config.yml themes/Paper-White/_config.yml #拷贝个人主题配置
  - npm install hexo-cli -g
install:
  - npm install
script:
  - hexo clean && hexo g
after_script:
  - git config --global user.name "xingoxu"
  - git config --global user.email "xingoxu@gmail.com"
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - sed -i'' "s~${GH_REF}~${GH_TOKEN}:x-oauth-basic@${GH_REF}~" _config.yml #将配置中的地址改成github api地址
  - hexo d > log.txt 2>&1 #deploy输出重定位
  - cat log.txt | sed "s~${GH_TOKEN}~TOKEN~g" #输出deploy内容并替换掉token
branches:
  only:
  - source
env:
  global:
  - GH_REF: github.com/xingoxu/xingoxu.github.io.git

