# Header
menu:
  home: /
  archives: /archives
  profile: /about
  works: http://works.xingoxu.com/

# SubNav
subnav:
  github: "https://github.com/xingoxu"
  weibo: "https://weibo.com/pokemonxu/"
  #facebook: "#"
  #google: "#"
  twitter: "https://twitter.com/xingoxu"
  bangumi: "https://bgm.tv/user/xingo"
  mail: "mailto:admin@xingoxu.com"
  rss: "/atom.xml"
  #linkedin: "#"

rss: /atom.xml

top_homepage: https://xingoxu.com/ #顶层主页，比如有主站等，将会应用在头像上 

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.

# Miscellaneous
google_analytics: 'UA-91877583-1'
favicon: /favicon.ico

#你的头像url
avatar: https://dn-xingoxu.qbox.me/avatar.png
#是否开启分享
share: true
shareid: 
  tsina: 1804320382
  twitter: xingoxu
#  google_plus: 
#  fb_admins: 
#  fb_app_id: 

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: blog-xingoxu

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  SmdCn's Blog: https://blog.smdcn.net/ 
  Carpe Diem: http://blog.d0zingcat.xyz/


#是否开启“关于我”。
#不开启——
aboutme: false
#开启——
#aboutme: 愿能一直像个小男孩一样仰望未来......
# 头图
titlepic: https://dn-xingoxu.qbox.me/blog_theme/banner_v2.png

bangumi_update_api: https://updates.xingoxu.com/bangumi/timeline 